### ISSUE TITLE
لاراول 9

### ISSUE THREAD

**Issue by yousof-jfri** [Tohidda/payping#4]
سلام ، ممنون بابت پکیج عالی تون اما یه مسئله که در حال حاضر چند ماهی میشه که لاراول 9 وارد بازار شده و از شما خواهش مندم که آپدیت pay ping برای لاراول 9 رو هرچه سریع تر عرضه کنید و لطفا وقتی یک پکیج رو توسعه میدید درست توسعه بدین

**Comment by sajaddp** [comment]
آقا نسخه ۱۰ هم داره میاد. خب چرا پشتیبانی نمی کنید؟!
@tdanandeh

**Comment by tdanandeh** [comment]
برای لاراول 10 هم توسعه داده شد
